name: hpc_env  # Replace with the desired name of your environment
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.11
  - scikit-learn 
  - networkx  
  - matplotlib
  - numba  
  - ipykernel
  - swig
  - jax
  - jaxlib
  - rich
  - memory_profiler
  - line_profiler
